### ISSUE TITLE
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\rfid\index.php on line 24

### ISSUE THREAD

**Issue by dedyrizaldi** [lintangtimur/RFID-absensi#6]
Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\rfid\index.php on line 24

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\rfid\index.php on line 24

error di bagian itu kenapa yah mas kalau boleh tau database sudah saya import sesuai dengan petunjuk yg mas berikan...

**Comment by lintangtimur** [comment]
di dalam folder project jalankan perintah
`composer install`

**Comment by dedyrizaldi** [comment]
> di dalam folder project jalankan perintah
> `composer install`

Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\xampp\htdocs\rfid\.env. in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php:106 Stack trace: #0 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php(83): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(114): Dotenv\Loader->load() #2 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(52): Dotenv\Dotenv->loadData() #3 C:\xampp\htdocs\rfid\index.php(30): Dotenv\Dotenv->load() #4 {main} thrown in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php on line 106

sudah di install composernya tp error sprt itu mas

**Comment by lintangtimur** [comment]
> 
> 
> > di dalam folder project jalankan perintah
> > `composer install`
> 
> Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\xampp\htdocs\rfid.env. in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php:106 Stack trace: #0 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php(83): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(114): Dotenv\Loader->load() #2 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(52): Dotenv\Dotenv->loadData() #3 C:\xampp\htdocs\rfid\index.php(30): Dotenv\Dotenv->load() #4 {main} thrown in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php on line 106
> 
> sudah di install composernya tp error sprt itu mas

rename `.env-example` menjadi `.env`, lalu sesuai kan isi file ENV tersebut
driver diisi mysql
host diisi localhost

**Comment by dedyrizaldi** [comment]
> > > di dalam folder project jalankan perintah
> > > `composer install`
> > 
> > 
> > Fatal error: Uncaught Dotenv\Exception\InvalidPathException: Unable to read the environment file at C:\xampp\htdocs\rfid.env. in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php:106 Stack trace: #0 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php(83): Dotenv\Loader->ensureFileIsReadable() #1 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(114): Dotenv\Loader->load() #2 C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Dotenv.php(52): Dotenv\Dotenv->loadData() #3 C:\xampp\htdocs\rfid\index.php(30): Dotenv\Dotenv->load() #4 {main} thrown in C:\xampp\htdocs\rfid\vendor\vlucas\phpdotenv\src\Loader.php on line 106
> > sudah di install composernya tp error sprt itu mas
> 
> rename `.env-example` menjadi `.env`, lalu sesuai kan isi file ENV tersebut
> driver diisi mysql
> host diisi localhost

terimakasih banyak mas sudah bisa... 
izin untuk saya kembangkan ya mas untuk tugas akhir saya terimakasih...

**Comment by lintangtimur** [comment]
silahkan

**Comment by masaahh** [comment]
USERDB="<your database username>"
PASSWORD="<your db psasword>"

ini maksudnya apa ya mas?

**Comment by masaahh** [comment]
cara instal composer nya gmna mas?

**Comment by bbennyputra** [comment]
composer install

**Comment by anggit-marcellino** [comment]
> 
> 
> composer install

buka cmd

1 . composer ( jika sudah menginstal composer sebelumnya )

2. cd \

3. cd xampp

4. cd htdocs

5.cd nama project

6. composer instal

**Comment by fajarrkurniawan** [comment]
[Tue May 18 01:34:04 2021] PHP Warning:  require(C:\xampp2\htdocs\kasir\public/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp2\htdocs\kasir\public\index.php on line 24
[Tue May 18 01:34:04 2021] PHP Fatal error:  require(): Failed opening required 'C:\xampp2\htdocs\kasir\public/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\xampp2\htdocs\kasir\public\index.php on line 24
[Tue May 18 01:34:04 2021] [::1]:60171 [500]: GET / - require(): Failed opening required 'C:\xampp2\htdocs\kasir\public/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\xampp2\htdocs\kasir\public\index.php on line 24
[Tue May 18 01:34:05 2021] [::1]:60171 Closing


Kenpa ya bang kalo kek gini?

**Comment by Ariski-Surahman** [comment]
Peringatan : require_once(C:\xampp\phpMyAdmin\vendor/composer/autoload_real.php): Gagal membuka streaming: Tidak ada file atau direktori di C:\xampp\phpMyAdmin\vendor\autoload.php on line 5

Kesalahan fatal : Tidak tertangkap Kesalahan: Gagal membuka 'C:\xampp\phpMyAdmin\vendor/composer/autoload_real.php' (include_path='C:\xampp\php\PEAR') di C:\xampp\phpMyAdmin\vendor\autoload.php:5 Stack trace: #0 C:\xampp\phpMyAdmin\index.php(36): require() #1 {main} dilemparkan ke dalam C:\xampp\phpMyAdmin\vendor\autoload.php pada baris 5
ini cara ngatasi erornya gmna?

**Comment by murizal555** [comment]
PHP Warning:  require(/media/ijal/data/Murizal/hotel/vendor/autoload.php): Failed to open stream: No such file or directory in /media/ijal/data/Murizal/hotel/artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required '/media/ijal/data/Murizal/hotel/vendor/autoload.php' (include_path='.:/usr/share/php') in /media/ijal/data/Murizal/hotel/artisan:18
Stack trace:
#0 {main}


kenapa seperti ini di laravel soalnya saya copy di teman folder nya?

**Comment by Cindyprasasty** [comment]
PHP Warning:  require(C:\xampp\htdocs\Epower/vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\Epower\artisan on line 18

Warning: require(C:\xampp\htdocs\Epower/vendor/autoload.php): Failed to open stream: No such file or directory in C:\xampp\htdocs\Epower\artisan on line 18
PHP Fatal error:  Uncaught Error: Failed opening required 'C:\xampp\htdocs\Epower/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Epower\artisan:18
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\Epower\artisan on line 18

Fatal error: Uncaught Error: Failed opening required 'C:\xampp\htdocs\Epower/vendor/autoload.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\Epower\artisan:18
Stack trace:
#0 {main}
  thrown in C:\xampp\htdocs\Epower\artisan on line 18

kalau kaya gtu itu kenapa ya?

**Comment by bbennyputra** [comment]
Maaf dengan siapa ?

Pada tanggal Jum, 25 Agu 2023 11.41, Cindy Oktaviani Eka Prasasti <
***@***.***> menulis:

**Comment by lintangtimur** [comment]
sementara project ini sedang saya update menggunakan teknologi terbarukan (Laravel), tidak dengan native lagi

**Comment by bbennyputra** [comment]
Done!
